include:
- testnet/docker-compose.yml
services:
  workload:
    image: workload:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workload
    hostname: workload
    ports:
    - 8000:8000
    init: true
    restart: on-failure
    depends_on:
      rippled:
        condition: service_started
    networks:
      xrpl_net: {}
    volumes:
    - ./testnet/accounts.json:/workload/testnet/accounts.json:ro
